import type { MarketDetail, MarketSummary, NewsItem } from "@/lib/types";

export const fallbackNews: NewsItem[] = [
  {
    id: "fallback-boj-1",
    title: "日本銀行 金融政策決定会合に関する公表資料",
    source: "日本銀行",
    publishedAt: "2026-06-15T00:00:00.000Z",
    url: "https://www.boj.or.jp/",
    category: "日銀",
    relatedMarket: "日銀は次回会合で利上げする？",
    summary: "金融政策・物価見通し・会合日程を確認するための公式情報です。",
    kind: "公式情報",
    status: "fallback",
  },
  {
    id: "fallback-kokkai-1",
    title: "国会会議録: 予測市場と金融規制に関する発言",
    source: "国会会議録",
    publishedAt: "2026-04-21T00:00:00.000Z",
    url: "https://kokkai.ndl.go.jp/",
    category: "規制",
    relatedMarket: "暗号資産税制改正は年内に進む？",
    summary: "予測市場、暗号資産、金融規制の論点を追うための一次情報です。",
    kind: "公式情報",
    status: "fallback",
  },
  {
    id: "fallback-egov-1",
    title: "e-Gov パブリックコメント 新着案件",
    source: "e-Gov",
    publishedAt: "2026-06-15T00:00:00.000Z",
    url: "https://public-comment.e-gov.go.jp/pcm/list",
    category: "政策",
    relatedMarket: "日本の規制関連市場",
    summary: "金融、税制、デジタル政策に関する新着案件を確認します。",
    kind: "公式情報",
    status: "fallback",
  },
];

export const fallbackMarkets: MarketSummary[] = [
  {
    id: "sample-boj-rate",
    slug: "sample-boj-rate",
    title: "日銀は次回会合で利上げする？",
    originalTitle: "Bank of Japan Decision in June?",
    summaryJa: "次回金融政策決定会合で短期政策金利の上限が引き上げられるかを見る市場です。",
    category: "日銀",
    probability: 0.42,
    yesPrice: 0.42,
    noPrice: 0.58,
    bestBid: 0.41,
    bestAsk: 0.43,
    spread: 0.02,
    volume: 208564,
    volume24h: 23291,
    volume1w: 89917,
    volume1m: 184227,
    liquidity: 32442,
    endDate: "2026-06-16T00:00:00.000Z",
    updatedAt: "2026-06-15T00:00:00.000Z",
    relatedNewsCount: 3,
    status: "fallback",
    source: "Fallback sample",
    url: "https://polymarket.com/",
  },
  {
    id: "sample-election",
    slug: "sample-election",
    title: "参院選で与党は過半数維持？",
    originalTitle: "Japan election market",
    summaryJa: "日本の選挙情勢に関連する予測市場の表示例です。",
    category: "選挙",
    probability: 0.55,
    yesPrice: 0.55,
    noPrice: 0.45,
    bestBid: 0.54,
    bestAsk: 0.57,
    spread: 0.03,
    volume: 93420,
    volume24h: 8200,
    volume1w: 24000,
    volume1m: 93420,
    liquidity: 15500,
    endDate: "2026-07-31T00:00:00.000Z",
    updatedAt: "2026-06-15T00:00:00.000Z",
    relatedNewsCount: 2,
    status: "fallback",
    source: "Fallback sample",
    url: "https://polymarket.com/",
  },
  {
    id: "sample-crypto-tax",
    slug: "sample-crypto-tax",
    title: "暗号資産税制改正は年内に進む？",
    originalTitle: "Japan crypto regulation by year-end?",
    summaryJa: "暗号資産、税制、金融庁の制度改正に関する予測市場の表示例です。",
    category: "規制",
    probability: 0.35,
    yesPrice: 0.35,
    noPrice: 0.65,
    bestBid: 0.33,
    bestAsk: 0.37,
    spread: 0.04,
    volume: 42100,
    volume24h: 3900,
    volume1w: 12000,
    volume1m: 42100,
    liquidity: 8900,
    endDate: "2026-12-31T00:00:00.000Z",
    updatedAt: "2026-06-15T00:00:00.000Z",
    relatedNewsCount: 4,
    status: "fallback",
    source: "Fallback sample",
    url: "https://polymarket.com/",
  },
  {
    id: "sample-yen",
    slug: "sample-yen",
    title: "USD/JPYは一定水準を超える？",
    originalTitle: "Will USD/JPY cross a key level?",
    summaryJa: "円相場と米ドル/円の水準に関する予測市場の表示例です。",
    category: "為替",
    probability: 0.62,
    yesPrice: 0.62,
    noPrice: 0.38,
    bestBid: 0.61,
    bestAsk: 0.64,
    spread: 0.03,
    volume: 118800,
    volume24h: 15300,
    volume1w: 62000,
    volume1m: 118800,
    liquidity: 22100,
    endDate: "2026-09-30T00:00:00.000Z",
    updatedAt: "2026-06-15T00:00:00.000Z",
    relatedNewsCount: 2,
    status: "fallback",
    source: "Fallback sample",
    url: "https://polymarket.com/",
  },
];

export function fallbackDetail(id: string): MarketDetail {
  const market = fallbackMarkets.find((item) => item.id === id) ?? fallbackMarkets[0];
  return {
    ...market,
    description:
      "実データの取得に失敗した場合に表示する社内デモ用の説明です。実装では Polymarket の市場説明と解決条件を表示します。",
    resolutionSource: "Polymarket market page and official resolution source",
    clobTokenIds: [],
    outcomes: ["Yes", "No"],
    priceHistory: [
      { label: "7日前", value: Math.max(0.05, market.probability - 0.06) },
      { label: "5日前", value: Math.max(0.05, market.probability - 0.02) },
      { label: "3日前", value: market.probability + 0.01 },
      { label: "昨日", value: Math.max(0.05, market.probability - 0.01) },
      { label: "現在", value: market.probability },
    ],
    volumeHistory: [
      { label: "24h", value: market.volume24h ?? market.volume * 0.12 },
      { label: "7d", value: market.volume1w ?? market.volume * 0.42 },
      { label: "30d", value: market.volume1m ?? market.volume * 0.72 },
      { label: "累計", value: market.volume },
    ],
    officialInfo: fallbackNews.slice(0, 2),
    relatedNews: fallbackNews,
    watchPoints: [
      "解決条件と一次情報の更新タイミングを先に確認する",
      "出来高と流動性が薄い市場は価格変動が大きくなりやすい",
      "価格は市場参加者の見方であり、発生確率の保証ではない",
    ],
  };
}
