CREATE TABLE "RealtimeMarketTick" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "eventId" TEXT,
    "marketId" TEXT NOT NULL,
    "positiveTokenId" TEXT NOT NULL,
    "negativeTokenId" TEXT NOT NULL,
    "asset" TEXT NOT NULL,
    "marketStartAt" DATETIME NOT NULL,
    "marketEndAt" DATETIME NOT NULL,
    "marketPhase" TEXT NOT NULL,
    "probability" REAL NOT NULL,
    "polymarketBestBid" REAL NOT NULL,
    "polymarketBestAsk" REAL NOT NULL,
    "polymarketBidSize" REAL,
    "polymarketAskSize" REAL,
    "polymarketSpread" REAL NOT NULL,
    "polymarketUpdatedAt" DATETIME NOT NULL,
    "negativeBestBid" REAL NOT NULL,
    "negativeBestAsk" REAL NOT NULL,
    "negativeBidSize" REAL,
    "negativeAskSize" REAL,
    "negativeSpread" REAL NOT NULL,
    "negativeUpdatedAt" DATETIME NOT NULL,
    "hyperliquidBestBid" REAL NOT NULL,
    "hyperliquidBestAsk" REAL NOT NULL,
    "hyperliquidBidSize" REAL,
    "hyperliquidAskSize" REAL,
    "hyperliquidSpread" REAL NOT NULL,
    "hyperliquidMidPrice" REAL NOT NULL,
    "hyperliquidMarkPrice" REAL,
    "hyperliquidOraclePrice" REAL,
    "hyperliquidFundingRate" REAL,
    "hyperliquidUpdatedAt" DATETIME NOT NULL,
    "chainlinkPrice" REAL,
    "chainlinkUpdatedAt" DATETIME,
    "binancePrice" REAL,
    "binanceUpdatedAt" DATETIME,
    "referencePrice" REAL NOT NULL,
    "referenceSource" TEXT NOT NULL,
    "referenceUpdatedAt" DATETIME NOT NULL,
    "priceBasisPct" REAL NOT NULL,
    "complementBidSum" REAL NOT NULL,
    "complementAskSum" REAL NOT NULL,
    "arbitrageViolation" BOOLEAN NOT NULL DEFAULT false,
    "captureSkewMs" INTEGER NOT NULL,
    "synchronizationVersion" TEXT NOT NULL,
    "capturedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "RealtimeMarketTick_marketId_capturedAt_idx" ON "RealtimeMarketTick"("marketId", "capturedAt");
CREATE INDEX "RealtimeMarketTick_asset_capturedAt_idx" ON "RealtimeMarketTick"("asset", "capturedAt");
CREATE INDEX "RealtimeMarketTick_capturedAt_captureSkewMs_idx" ON "RealtimeMarketTick"("capturedAt", "captureSkewMs");
CREATE INDEX "RealtimeMarketTick_synchronizationVersion_capturedAt_idx" ON "RealtimeMarketTick"("synchronizationVersion", "capturedAt");
